import fs from 'node:fs';
import path from 'node:path';
import { buildPools, cultures, types } from './data-lib.ts';
const {records,stats,collisions}=buildPools();
const lines=['# Data report','','Generated by `npm run data:report`.','','## Counts','','| Pool/type | Raw | Missing | Non-Latin | Too long | Brackets | Duplicate | Ambiguous | Blocklist | Kept |','|---|---:|---:|---:|---:|---:|---:|---:|---:|---:|'];
for(const [k,s] of Object.entries(stats)) lines.push(`| ${k} | ${s.raw} | ${s.missing} | ${s.nonLatin} | ${s.tooLong} | ${s.brackets} | ${s.duplicate} | ${s.ambiguous} | ${s.blocklisted} | ${s.kept} |`);
lines.push('','## Cross-pool collisions','',...(collisions.length?collisions.map(c=>`- ${c.key}: ${c.cultures.join(', ')}`):['None.']),'','## Deterministic review samples','');
for(const culture of cultures) for(const type of types){
  const vals=records.filter(r=>r.culture===culture&&r.type===type).map(r=>r.en);
  const step=Math.max(1,Math.floor(vals.length/15));
  lines.push(`### ${culture} / ${type}`,'',vals.filter((_,i)=>i%step===0).slice(0,15).join(' · ')||'_No usable entries_','');
}
fs.mkdirSync('docs',{recursive:true}); fs.writeFileSync(path.join('docs','DATA_REPORT.md'),lines.join('\n'));
console.log('Wrote docs/DATA_REPORT.md');
