import {useEffect,useMemo,useRef,useState} from 'preact/hooks';
import en from './i18n/en.json';import zh from './i18n/zh.json';
import {CULTURES,GROUPS,type Culture,type Difficulty,type Group,type Pool,type Round} from './engine/types';
import {generateSession,groupAccuracy,scoreAnswer} from './engine/game';
import {Logo} from './ui/Logo';import {Radar} from './ui/Radar';import {shareCard} from './share/card';

type Lang='en'|'zh';type Screen='home'|'select'|'loading'|'game'|'results'|'old';
type Config={posterNumber:string;voteUrl:string;paperUrl:string;posterUrl:string;repoUrl:string;gameRepoUrl:string;rounds:number;timerSeconds:number;minPool:number};
type Manifest={dataVersion:string;counts:Record<string,Record<string,number>>};
const defaults:Config={posterNumber:'',voteUrl:'',paperUrl:'https://arxiv.org/abs/2510.05291',posterUrl:'',repoUrl:'',gameRepoUrl:'',rounds:12,timerSeconds:12,minPool:10};
const cultureMeta:Record<Culture,{en:string;zh:string;glyph:string;flag:string;color:string}>={chinese:{en:'Chinese',zh:'中国',glyph:'中',flag:'🇨🇳',color:'#E5484D'},japanese:{en:'Japanese',zh:'日本',glyph:'日',flag:'🇯🇵',color:'#5B6CFF'},korean:{en:'Korean',zh:'韩国',glyph:'한',flag:'🇰🇷',color:'#22C3B5'},vietnamese:{en:'Vietnamese',zh:'越南',glyph:'Việt',flag:'🇻🇳',color:'#F5B301'},pakistani:{en:'Pakistani',zh:'巴基斯坦',glyph:'پ',flag:'🇵🇰',color:'#2FB463'},indian:{en:'Indian',zh:'印度',glyph:'भ',flag:'🇮🇳',color:'#FF9933'},western:{en:'Western',zh:'西方',glyph:'◎',flag:'🌐',color:'#94A3B8'}};
const PICKER_ORDER:Culture[]=['chinese','indian','japanese','korean','pakistani','vietnamese'];
const groupNames:Record<Lang,Record<Group,string>>={en:{authors:'Authors',beverage:'Drinks',food:'Food',locations:'Places',names:'Names',sports:'Sports'},zh:{authors:'作家',beverage:'饮品',food:'美食',locations:'地点',names:'名字',sports:'球队'}};
const prompts:Record<Lang,Record<string,string>>={en:{authors:'Which of these is a {culture} author?',beverage:'Which of these is a {culture} drink?',food:'Which of these is a {culture} dish?',locations:'Which of these is a place in {culture}?',names_m:'Which is a {culture} male first name?',names_f:'Which is a {culture} female first name?',sports:'Which of these is a {culture} sports club?'},zh:{authors:'哪一位是{culture}作家？',beverage:'哪一个是{culture}饮品？',food:'哪一道是{culture}美食？',locations:'哪一个地点位于{culture}？',names_m:'哪一个是{culture}男性的名字？',names_f:'哪一个是{culture}女性的名字？',sports:'哪一个是{culture}球队？'}};
const safeGet=(k:string,fallback:string)=>{try{return localStorage.getItem(k)||fallback}catch{return fallback}};const safeSet=(k:string,v:string)=>{try{localStorage.setItem(k,v)}catch{/* private mode */}};
const randomSeed=()=>Math.random().toString(36).slice(2,8);
function parseChallenge(){const raw=location.hash.split('?')[1];if(!raw)return null;const p=new URLSearchParams(raw);const c=p.get('c') as Culture,d=p.get('d') as Difficulty;if(!CULTURES.includes(c)||!['easy','standard','hard'].includes(d))return null;return{culture:c,difficulty:d,seed:p.get('s')||randomSeed(),version:p.get('v')||'',from:p.get('from')||'',score:Number(p.get('score')||0)}}
function titleFor(correct:number,lang:Lang){const table=lang==='zh'?['迷失在翻译中','好奇的游客','半个本地人','认证圈内人','文化百科全书']:['Lost in Translation','Curious Tourist','Local-ish','Certified Insider','Cultural Encyclopedia'];return correct===12?table[4]:correct>=10?table[3]:correct>=7?table[2]:correct>=4?table[1]:table[0]}
function beep(ok:boolean){try{const C=window.AudioContext||(window as unknown as {webkitAudioContext:typeof AudioContext}).webkitAudioContext,c=new C(),o=c.createOscillator(),g=c.createGain();o.frequency.value=ok?660:180;g.gain.setValueAtTime(.08,c.currentTime);g.gain.exponentialRampToValueAtTime(.001,c.currentTime+.16);o.connect(g).connect(c.destination);o.start();o.stop(c.currentTime+.16)}catch{/* optional */}}

export default function App(){
 const initialLang=safeGet('ck-lang',navigator.language.startsWith('zh')?'zh':'en') as Lang;
 const [lang,setLang]=useState<Lang>(initialLang);const t=(k:keyof typeof en,vars:Record<string,string|number>={})=>String((lang==='zh'?zh:en)[k]).replace(/\{(\w+)\}/g,(_,x)=>String(vars[x]??''));
 const [screen,setScreen]=useState<Screen>('home'),[about,setAbout]=useState(false);const [difficulty,setDifficulty]=useState<Difficulty>(safeGet('ck-difficulty','standard') as Difficulty);const [relaxed,setRelaxed]=useState(safeGet('ck-relaxed','0')==='1'),[sound,setSound]=useState(safeGet('ck-sound','0')==='1');
 const [config,setConfig]=useState(defaults),[manifest,setManifest]=useState<Manifest|null>(null),[culture,setCulture]=useState<Culture>('chinese'),[seed,setSeed]=useState(''),[rounds,setRounds]=useState<Round[]>([]);const [current,setCurrent]=useState(0),[picked,setPicked]=useState<number|null>(null),[revealed,setRevealed]=useState(false),[answers,setAnswers]=useState<boolean[]>([]),[score,setScore]=useState(0),[streak,setStreak]=useState(0),[timeLeft,setTimeLeft]=useState(12),[notice,setNotice]=useState('');const [challenger,setChallenger]=useState<{from:string;score:number}|null>(null);
 const deadline=useRef(0),challengeHandled=useRef(false);
 useEffect(()=>{Promise.all([fetch(`${import.meta.env.BASE_URL}site.config.json`).then(r=>r.json()).catch(()=>defaults),fetch(`${import.meta.env.BASE_URL}data/manifest.json`).then(r=>r.json())]).then(([c,m])=>{setConfig({...defaults,...c});setManifest(m)})},[]);
 useEffect(()=>{document.documentElement.lang=lang==='zh'?'zh-CN':'en';safeSet('ck-lang',lang)},[lang]);
 useEffect(()=>{if(!manifest||challengeHandled.current)return;const ch=parseChallenge();if(!ch)return;challengeHandled.current=true;if(ch.version&&ch.version!==manifest.dataVersion){setScreen('old');return}setDifficulty(ch.difficulty);setChallenger(ch.from?{from:ch.from,score:ch.score}:null);void start(ch.culture,ch.seed,ch.difficulty)},[manifest]);
 useEffect(()=>{if(screen!=='game'||revealed||relaxed)return;deadline.current=Date.now()+config.timerSeconds*1000;setTimeLeft(config.timerSeconds);const id=window.setInterval(()=>{const left=Math.max(0,(deadline.current-Date.now())/1000);setTimeLeft(left);if(left<=0){clearInterval(id);answer(null)}},100);return()=>clearInterval(id)},[screen,current,revealed,relaxed]);
 useEffect(()=>{const key=(e:KeyboardEvent)=>{if(screen==='game'&&!revealed&&/^[1-4]$/.test(e.key))answer(Number(e.key)-1);else if(screen==='game'&&revealed&&(e.key==='Enter'||e.key===' ')){e.preventDefault();next()}};addEventListener('keydown',key);return()=>removeEventListener('keydown',key)});
 async function loadPools(){return Promise.all(CULTURES.map(c=>fetch(`${import.meta.env.BASE_URL}data/pool.${c}.json`).then(r=>{if(!r.ok)throw new Error('Data unavailable');return r.json()}))) as Promise<Pool[]>}
 async function start(c:Culture,s=randomSeed(),d=difficulty){setScreen('loading');setCulture(c);setSeed(s);setCurrent(0);setPicked(null);setRevealed(false);setAnswers([]);setScore(0);setStreak(0);try{const pools=await loadPools();setRounds(generateSession({culture:c,difficulty:d,seed:s,rounds:config.rounds,pools,minPool:config.minPool}));setScreen('game')}catch(e){setNotice(e instanceof Error?e.message:'Could not load data');setScreen('select')}}
 function answer(index:number|null){if(revealed||screen!=='game')return;const r=rounds[current];if(!r)return;const ok=index===r.correctIndex;setPicked(index);setRevealed(true);setAnswers(a=>[...a,ok]);if(ok){setScore(v=>v+scoreAnswer(true,relaxed?config.timerSeconds:timeLeft,streak,config.timerSeconds));setStreak(s=>s+1)}else setStreak(0);if(sound)beep(ok);navigator.vibrate?.(ok?20:[35,30,35])}
 function next(){if(!revealed)return;if(current>=rounds.length-1){setScreen('results');try{safeSet(`ck-best-${culture}`,String(Math.max(score,Number(safeGet(`ck-best-${culture}`,'0')))));safeSet('ck-games',String(Number(safeGet('ck-games','0'))+1))}catch{}return}setCurrent(i=>i+1);setPicked(null);setRevealed(false)}
 const correct=answers.filter(Boolean).length;const stats=useMemo(()=>rounds.length?groupAccuracy(rounds,answers):Object.fromEntries(GROUPS.map(g=>[g,null])) as Record<Group,number|null>,[rounds,answers]);
 function challengeUrl(name=''){if(!manifest)return location.href;const u=new URL(location.href);u.hash=`/play?${new URLSearchParams({c:culture,d:difficulty,s:seed,v:manifest.dataVersion,...(name?{from:name,score:String(score)}:{})})}`;return u.href}
 async function makeChallenge(){const url=challengeUrl();try{if(navigator.share)await navigator.share({title:'Test-Your-CK',text:`${t('challenge')} — ${score}`,url});else{await navigator.clipboard.writeText(url);setNotice(t('copied'))}}catch{/* cancelled */}}
 const currentRound=rounds[current];const cultureName=(c:Culture)=>cultureMeta[c][lang];
 return <div class="app" style={{'--culture':cultureMeta[culture].color}}>
  <div class="petals" aria-hidden="true"><i/><i/><i/></div>
  <header><button class="brand" onClick={()=>setScreen('home')} aria-label="Home"><Logo small/><span>Test-Your-CK</span></button><div class="header-actions"><button class="icon-btn" onClick={()=>{setSound(v=>{safeSet('ck-sound',v?'0':'1');return!v})}} aria-label={t('sound')}>{sound?'♪':'♩'}</button><button class="lang" onClick={()=>setLang(l=>l==='en'?'zh':'en')}>{lang==='en'?'中文':'EN'}</button><button class="icon-btn" onClick={()=>setAbout(true)} aria-label={t('about')}>ⓘ</button></div></header>
  <main>
   {screen==='home'&&<section class="hero"><Logo/><p class="eyebrow">CULTURAL KNOWLEDGE · 12 ROUNDS</p><h1>{t('title')}</h1><p class="tagline">{t('tagline')}</p><button class="primary jumbo" onClick={()=>setScreen('select')}>{t('play')} <span>→</span></button><div class="home-footer"><p class="credit">Camellia</p><p>Made with ❤️ by Sahajpreet</p></div></section>}
   {screen==='select'&&<section class="panel select"><button class="back" onClick={()=>setScreen('home')}>←</button><p class="step">01 / 02</p><h2>{t('pickCulture')}</h2><div class="difficulty" role="group" aria-label={t('difficulty')}>{(['easy','standard','hard'] as Difficulty[]).map(d=><button class={difficulty===d?'active':''} onClick={()=>{setDifficulty(d);safeSet('ck-difficulty',d)}}>{t(d)}</button>)}</div><div class="culture-grid">{PICKER_ORDER.map(c=><button class="culture-tile" style={{'--tile':cultureMeta[c].color}} onClick={()=>void start(c)}><span class="flag" aria-hidden="true">{cultureMeta[c].flag}</span><b>{cultureName(c)}</b><small>{cultureMeta[c].en}</small></button>)}</div><label class="toggle"><input type="checkbox" checked={relaxed} onChange={e=>{const v=e.currentTarget.checked;setRelaxed(v);safeSet('ck-relaxed',v?'1':'0')}}/><span/>{t('relaxed')}</label>{notice&&<p class="notice">{notice}</p>}</section>}
   {screen==='loading'&&<section class="center"><div class="loader"><Logo/></div><p>{t('loading')}</p></section>}
   {screen==='old'&&<section class="center"><Logo/><h2>{t('freshChallenge')}</h2><button class="primary" onClick={()=>{location.hash='';setScreen('select')}}>{t('play')}</button></section>}
   {screen==='game'&&currentRound&&<section class="game"><div class="game-top"><span>{t('round')} <b>{current+1}</b> / {rounds.length}</span><span>{streak>=3&&<i class="flame">◆ {streak}</i>} {t('score')} <b>{score}</b></span></div>{!relaxed&&<div class="timer" aria-label={`${Math.ceil(timeLeft)} seconds`}><i style={{transform:`scaleX(${timeLeft/config.timerSeconds})`}}/></div>}<p class="category">{groupNames[lang][currentRound.group]}</p><h2>{prompts[lang][currentRound.type].replace('{culture}',cultureName(culture))}</h2><div class={`options ${revealed?'revealed':''}`}>{currentRound.options.map((o,i)=>{const isCorrect=i===currentRound.correctIndex,isWrong=revealed&&picked===i&&!isCorrect;return <button class={`option ${revealed&&isCorrect?'correct':''} ${isWrong?'wrong':''}`} disabled={revealed} onClick={()=>answer(i)} style={{'--delay':`${i*55}ms`}}><span class="number">{i+1}</span><b>{o.en}</b>{revealed&&<span class="reveal"><em class="flag-emoji">{cultureMeta[o.culture].flag}</em>{cultureName(o.culture)} {isCorrect&&<strong>✓</strong>}{isWrong&&<strong>✕</strong>}</span>}</button>})}</div>{revealed&&<div class="feedback"><b>{t(picked===currentRound.correctIndex?'correct':picked===null?'timeout':'wrong')}</b>{config.gameRepoUrl&&<a href={`${config.gameRepoUrl}/issues/new?${new URLSearchParams({title:`Label report: ${currentRound.options[picked??currentRound.correctIndex].en}`,body:`Entity: ${currentRound.options[picked??currentRound.correctIndex].id}\nCulture: ${currentRound.options[picked??currentRound.correctIndex].culture}\nType: ${currentRound.type}`})}`} target="_blank">{t('report')}</a>}</div>}<div class="game-spacer"/>{revealed&&<button class="primary next" onClick={next}>{t('next')}</button>}</section>}
   {screen==='results'&&<section class="results"><p class="eyebrow">{t('results')}</p><div class="score-ring"><strong>{score}</strong><span>{t('score')}</span></div><h1>{titleFor(correct,lang)}</h1><p class="accuracy">{t('accuracy')} <b>{correct}/{rounds.length}</b></p>{challenger&&<p class="versus">{t('youVs',{name:challenger.from})}: <b>{score}</b> — <b>{challenger.score}</b></p>}<Radar values={stats} label={g=>groupNames[lang][g]}/><div class="did-you-know"><span>CAMELLIA PAPER</span><p>{t('paperTeaser')}</p><a href={config.paperUrl} target="_blank" rel="noreferrer">{t('readPaper')} ↗</a></div>{config.posterNumber&&config.voteUrl&&<a class="vote" href={config.voteUrl} target="_blank"><b>{t('vote',{n:config.posterNumber})}</b><span>{t('voteButton')} →</span></a>}<div class="result-actions"><button class="primary" onClick={()=>void shareCard({culture,cultureName:cultureName(culture),score,correct,title:titleFor(correct,lang),url:challengeUrl(),radar:GROUPS.map(g=>stats[g])})}>{t('share')}</button><button class="secondary" onClick={()=>void makeChallenge()}>{t('challenge')}</button><button class="secondary" onClick={()=>void start(culture)}>{t('again')}</button><button class="text-btn" onClick={()=>setScreen('select')}>{t('other')}</button></div>{notice&&<div class="toast">{notice}</div>}</section>}
  </main>
  {about&&<div class="modal-backdrop"><section class="modal about-page" role="dialog" aria-modal="true"><button class="modal-close" onClick={()=>setAbout(false)}>×</button><Logo/><h2>{t('about')} Camellia</h2><p>{t('aboutText')}</p><hr/><p>{t('association')}</p><p class="disclaimer">{t('disclaimer')}</p><hr/><div class="links"><a href={config.paperUrl} target="_blank">{t('readPaper')} ↗</a>{config.posterUrl&&<a href={config.posterUrl}>Poster ↗</a>}{config.repoUrl&&<a href={config.repoUrl}>Dataset ↗</a>}</div>{config.posterNumber&&config.voteUrl&&<a class="primary" href={config.voteUrl}>{t('voteButton')} #{config.posterNumber}</a>}<small>{t('attribution')}</small><p class="made-by">Made with ❤️ by Sahajpreet</p></section></div>}
 </div>
}
